/*
 * X9 API
 *
 * Moov X9 () implements an HTTP API for creating, parsing and validating X9 (Check21) files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RoutingNumberSummary struct {
	// RoutingNumberSummary ID
	Id string `json:"id,omitempty"`
	// CashLetterRoutingNumber is a number that identifies a given payor bank within a cash letter containing one or more payor banks.
	CashLetterRoutingNumber string `json:"cashLetterRoutingNumber"`
	// RoutingNumberTotalAmount is the total amount for all Check Detail Records associated with the Payor bank routing number designated in the Routing Number within Cash Letter.
	RoutingNumberTotalAmount int32 `json:"routingNumberTotalAmount,omitempty"`
	// RoutingNumberItemCount is the the total number of all Check Detail Records associated with the payor bank routing number designated in the Routing Number within Cash Letter.
	RoutingNumberItemCount int32 `json:"routingNumberItemCount,omitempty"`
	// UserField identifies a field used at the discretion of users of the standard.
	UserField string `json:"userField,omitempty"`
}
