/*
 * X9 API
 *
 * Moov X9 () implements an HTTP API for creating, parsing and validating X9 (Check21) files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type File struct {
	// File ID
	Id string `json:"id,omitempty"`
	FileHeader FileHeader `json:"fileHeader,omitempty"`
	CashLetters []CashLetter `json:"cashLetters,omitempty"`
	Bundles []Bundle `json:"bundles,omitempty"`
	FileControl FileControl `json:"fileControl,omitempty"`
}
