/*
 * ImageCashLetter API
 *
 * Moov Image Cash Letter (ICL) implements an HTTP API for creating, parsing, and validating ImageCashLetter files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BundleControl struct for BundleControl
type BundleControl struct {
	// BundleControl ID
	Id string `json:"id,omitempty"`
	// BundleItemsCount identifies the total number of items within the bundle.
	BundleItemsCount int32 `json:"bundleItemsCount"`
	// BundleTotalAmount identifies the total amount of item amounts within the bundle.
	BundleTotalAmount int32 `json:"bundleTotalAmount"`
	// MICRValidTotalAmount identifies the total amount of all Check Records within the bundle which contain 1 in the MICRValidIndicator.
	MicrValidTotalAmount int32 `json:"micrValidTotalAmount,omitempty"`
	// BundleImagesCount identifies the total number of ImageViewDetail Records  within the bundle.
	BundleImagesCount int32 `json:"bundleImagesCount,omitempty"`
	// UserField identifies a field used at the discretion of users of the standard.
	UserField string `json:"userField,omitempty"`
	// CreditTotalIndicator is a code that indicates whether Credit Items are included in the totals. If so, they will be included in this record’s BundleItemsCount, BundleTotalAmount, and BundleImagesCount. * ` ` - No Credit Items * `0` - Credit Items are not included in totals * `1` - Credit Items are included in totals
	CreditTotalIndicator int32 `json:"creditTotalIndicator,omitempty"`
}
