/*
 * ImageCashLetter API
 *
 * Moov Image Cash Letter (ICL) implements an HTTP API for creating, parsing, and validating ImageCashLetter files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IclFileControl struct for IclFileControl
type IclFileControl struct {
	// FileControl ID
	Id string `json:"id,omitempty"`
	// CashLetterCount identifies the total number of cash letters within the file.
	CashLetterCount int32 `json:"cashLetterCount"`
	// TotalRecordCount identifies the total number of records of all types sent in the file, including the FileControl.
	TotalRecordCount int32 `json:"totalRecordCount"`
	// totalItemCount identifies the total number of Items sent within the file.
	TotalItemCount int32 `json:"totalItemCount"`
	// FileTotalAmount identifies the total Item amount of the complete file.
	FileTotalAmount int32 `json:"fileTotalAmount"`
	// immediateOriginContactName identifies a contact at the institution that creates the file.
	ImmediateOriginContactName string `json:"immediateOriginContactName,omitempty"`
	// ImmediateOriginContactPhoneNumber identifies the phone number of the contact at the institution that creates the file.
	ImmediateOriginContactPhoneNumber string `json:"immediateOriginContactPhoneNumber,omitempty"`
	// CreditTotalIndicator is a code that indicates whether Credit Items are included in this record’s totals. If so, they will be included in TotalItemCount and FileTotalAmount. TotalRecordCount includes all records of all types regardless of the value of this field. * ` ` - No Credit Items * `0` - Credit Items are not included in totals * `1` - Credit Items are included in totals
	CreditTotalIndicator int32 `json:"creditTotalIndicator,omitempty"`
}
