/*
 * ImageCashLetter API
 *
 * Moov Image Cash Letter (ICL) implements an HTTP API for creating, parsing, and validating ImageCashLetter files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Checks struct for Checks
type Checks struct {
	// Check ID
	Id string `json:"id,omitempty"`
	// AuxiliaryOnUs identifies a code used on commercial checks at the discretion of the payor bank.
	AuxiliaryOnUs string `json:"auxiliaryOnUs,omitempty"`
	// ExternalProcessingCode identifies a code used for special purposes as authorized by the Accredited Standards Committee X9. Also known as Position 44.
	ExternalProcessingCode string `json:"externalProcessingCode,omitempty"`
	// PayorBankRoutingNumber identifies the institution by or through which the item is payable. Must be a valid routing and transit number issued by the ABA’s Routing Number Registrar. Shall represent the first 8 digits of a 9-digit routing number or 8 numeric digits of a 4 dash 4 routing number. A valid routing number consists of 2 fields: the eight-digit Payor Bank Routing Number and the one-digit Payor Bank Routing Number Check Digit.
	PayorBankRoutingNumber string `json:"payorBankRoutingNumber,omitempty"`
	// PayorBankCheckDigit identifies the routing number check digit.  The combination of Payor Bank Routing Number and Payor Bank Routing Number Check Digit must be a mod-checked routing number with a valid check digit.
	PayorBankCheckDigit string `json:"payorBankCheckDigit,omitempty"`
	// OnUs identifies data specified by the payor bank. On-Us data usually consists of the payor’s account number, a serial number or transaction code, or both.
	OnUs string `json:"onUs,omitempty"`
	// Amount identifies the amount of the check.  All amounts fields have two implied decimal points. e.g., 100000 is $1,000.00.
	ItemAmount int32 `json:"itemAmount,omitempty"`
	// ECEInstitutionItemSequenceNumber identifies a number assigned by the institution that creates the Check. Field must contain a numeric value. It cannot be all blanks.
	EceInstitutionItemSequenceNumber string `json:"eceInstitutionItemSequenceNumber,omitempty"`
	// DocumentationTypeIndicator identifies a code that indicates the type of documentation that supports the check record.  This field is superseded by the Cash Letter Documentation Type Indicator in the Cash Letter Header Record for all Defined Values except ‘Z’ Not Same Type. In the case of Defined Value of ‘Z’, the Documentation Type Indicator in this record takes precedent.  Shall be present when Cash Letter Documentation Type Indicator in the Cash Letter Header Record is Defined Value of ‘Z’.  * `A` - No image provided, paper provided separately * `B` - No image provided, paper provided separately, image upon request * `C` - Image provided separately, no paper provided * `D` - Image provided separately, no paper provided, image upon request * `E` - Image and paper provided separately * `F` - Image and paper provided separately, image upon request * `G` - Image included, no paper provided * `H` - Image included, no paper provided, image upon request * `I` - Image included, paper provided separately * `J` - Image included, paper provided separately, image upon request * `K` - No image provided, no paper provided * `L` - No image provided, no paper provided, image upon request * `M` - No image provided, Electronic Check provided separately
	DocumentationTypeIndicator string `json:"documentationTypeIndicator,omitempty"`
	// ReturnAcceptanceIndicator is a code that indicates whether the institution that creates the Check will or will not support electronic return processing.  * `0` - Will not accept any electronic information * `1` - Will accept preliminary return notifications, returns, and final return notifications * `2` - Will accept preliminary return notifications and returns * `3` - Will accept preliminary return notifications and final return notifications * `4` - Will accept returns and final return notifications * `5` - Will accept preliminary return notifications only * `6` - Will accept returns only * `7` - Will accept final return notifications only * `8` - Will accept preliminary return notifications, returns, final return notifications, and image returns * `9` - Will accept preliminary return notifications, returns and image returns * `A` - Will accept preliminary return notifications, final return notifications and image returns * `B` - Will accept returns, final return notifications and image returns * `C` - Will accept preliminary return notifications and image returns * `D` - Will accept returns and image returns * `E` - Will accept final return notifications and image returns * `F` - Will accept image returns only
	ReturnAcceptanceIndicator string `json:"returnAcceptanceIndicator,omitempty"`
	// MICRValidIndicator is a code that indicates whether any character in the Magnetic Ink Character Recognition (MICR) property is unreadable, or the OnUs property is missing from the Check. * `1` - Good read * `2` - Good read, missing field * `3` - Read error encountered * `4` - Missing field and read error encountered
	MicrValidIndicator int32 `json:"micrValidIndicator,omitempty"`
	// BOFDIndicator is a code that indicates whether the ECE institution indicated on the Bundle Header Record (Type 20) is the Bank of First Deposit (BOFD). This field shall be consistent with values contained in the Check Detail Addendum A Record (Type 26) and Check Detail Addendum C Record (Type 28). * `Y` - ECE institution is BOFD * `N` - ECE institution is not BOFD * `U` - ECE institution relationship to BOFD is undetermined
	BofdIndicator string `json:"bofdIndicator,omitempty"`
	// AddendumCount is a number of Check Detail Record Addenda to follow. This represents the number of CheckDetailAddendumA, CheckDetailAddendumB, and CheckDetailAddendumC types. It matches the total number of addendum records associated with this item. The standard supports up to 99 addendum records.
	AddendumCount int32 `json:"addendumCount,omitempty"`
	// CorrectionIndicator identifies whether and how the MICR line was repaired, for fields other than Payor Bank Routing Number and Amount. * `0` - No Repair * `1` - Repaired (form of repair unknown) * `2` - Repaired without Operator intervention * `3` - Repaired with Operator intervention * `4` - Undetermined if repair has been done or not
	CorrectionIndicator int32 `json:"correctionIndicator,omitempty"`
	// ArchiveTypeIndicator is a code that indicates the type of archive that supports this Check. Access method, availability, and time frames shall be defined by clearing arrangements.  * `A` - Microfilm * `B` - Image * `C` - Paper * `D` - Microfilm and image * `E` - Microfilm and paper * `F` - Image and paper * `G` - Microfilm, image and paper * `H` - Electronic Check Instrument * `I` - None
	ArchiveTypeIndicator string                 `json:"archiveTypeIndicator,omitempty"`
	CheckDetailAddendumA []CheckDetailAddendumA `json:"checkDetailAddendumA,omitempty"`
	CheckDetailAddendumB []CheckDetailAddendumB `json:"checkDetailAddendumB,omitempty"`
	CheckDetailAddendumC []CheckDetailAddendumC `json:"checkDetailAddendumC,omitempty"`
	ImageViewDetail      []ImageViewDetail      `json:"imageViewDetail,omitempty"`
	ImageViewData        []ImageViewData        `json:"imageViewData,omitempty"`
	ImageViewAnalysis    []ImageViewAnalysis    `json:"imageViewAnalysis,omitempty"`
}
