/*
 * ImageCashLetter API
 *
 * Moov Image Cash Letter (ICL) implements an HTTP API for creating, parsing and validating ImageCashLetter files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Returns struct for Returns
type Returns struct {
	ReturnDetail ReturnDetail `json:"returnDetail,omitempty"`
}
