FROM registry.access.redhat.com/ubi9/go-toolset as builder
COPY go.mod go.mod
COPY go.sum go.sum
COPY *.go ./
COPY ./cmd/server ./cmd/server
COPY makefile makefile
RUN make build-server

FROM registry.access.redhat.com/ubi9/ubi-minimal

ARG VERSION=unknown
LABEL maintainer="Moov <oss@moov.io>"
LABEL name="imagecashletter"
LABEL version=$VERSION

COPY --from=builder /opt/app-root/src/bin/server /bin/server

EXPOSE 8080
EXPOSE 9090
ENTRYPOINT ["/bin/server"]
