FROM golang:1.18 as builder
LABEL maintainer="Moov <support@moov.io>"
RUN apt-get update -qq && apt-get install -y git make

WORKDIR /go/src/github.com/gdamore/
RUN git clone https://github.com/gdamore/encoding.git

WORKDIR /go/src/github.com/moov-io/imagecashletter
COPY . .
RUN go mod vendor

WORKDIR /go/src/github.com/moov-io/imagecashletter/test/fuzz-reader
RUN make install
RUN make fuzz-build
ENTRYPOINT make fuzz-run
