openapi: 3.0.2
info:
  description: Moov X9 () implements an HTTP API for creating, parsing and validating X9 (Check21) files.
  version: v1
  title: X9 API
  contact:
    url: https://github.com/moov-io/x9
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8083
    description: Local development

tags:
  - name: Files
    description: |
      File contains X9 Cash Letters and Bundles.
paths:
  /ping:
    get:
      tags:
        - Files
      summary: Ping the Wire service to check if running
      operationId: ping
      responses:
        '200':
          description: Service is running properly
  /files:
    get:
      tags:
        - Files
      summary: Gets a list of Files
      operationId: getFiles
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - name: X-Request-Id
          in: header
          description: Optional Request ID allows application developer to trace requests through the systems logs
          example: rs4f9915
          schema:
            type: string
      responses:
        '200':
          description: A list of File objects


components:
  schemas:
    CreateFile:
      properties:
        id:
          type: string
          description: File ID
          example: 3f2d23ee214
        fileHeader:
          $ref: '#/components/schemas/FileHeader'
        cashLetters:
          type: array
          items:
            $ref: '#/components/schemas/CashLetter'
#        bundles:
#          type: array
#          items:
#            $ref: '#/components/schemas/Bundle'
        fileControl:
          $ref: '#/components/schemas/FileControl'
      required:
        - fileHeader
    File:
      properties:
        id:
          type: string
          description: File ID
          example: 3f2d23ee214
        fileHeader:
          $ref: '#/components/schemas/FileHeader'
        cashLetters:
          type: array
          items:
            $ref: '#/components/schemas/CashLetter'
#        bundles:
#          type: array
#          items:
#            $ref: '#/components/schemas/Bundle'
        fileControl:
          $ref: '#/components/schemas/FileControl'
    FileHeader:
      properties:
        id:
          description: CashHeader ID
          type: string
          example: d1e26288
        standardLevel:
          type: string
          maxLength: 2
          enum:
            - 03
            - 30
            - 35
          description: |
            Identifies the standard level of the file.

            * `03` - DSTU X9.37 - 2003
            * `30` - X9.100-187-2008
            * `35` - X9.100-187-2013 and 2016
          example: '35'
        testFileIndicator:
          type: string
          maxLength: 1
          enum:
            - T
            - P
          description: |
            Identifies whether the file is a test or production file.

            * `T` - Test File
            * `P` - Production File
          example: 'P'
        immediateDestination:
          type: string
          maxLength: 9
          description: |
            The routing and transit number of the Federal Reserve Bank (FRB)
            or receiver to which the file is being sent.
          example: '231380102'
        immediateOrigin:
          type: string
          maxLength: 9
          description: |
            The routing and transit number of the Federal Reserve Bank (FRB)
            or originator from which the file is being sent.
          example: '201982859'
        fileCreationDate:
          type: string
          maxLength: 8
          description: |
            The date that the immediate origin institution creates the file.
            (Format YYYYMMDD, where - YYYY year, MM month, DD day)
          example: '20190201'
        fileCreationTime:
          type: string
          maxLength: 4
          description: |
            The time the immediate origin institution creates the file.
            (Format - hhmm, where - hh hour, mm minute)
          example: '1310'
        resendIndicator:
          type: string
          maxLength: 1
          description: Indicates whether the file has been previously transmitted. (Y - Yes, N - No)
          example: 'Y'
        immediateDestinationName:
          type: string
          maxLength: 18
          description: Identifies the short name of the institution that receives the file.
          example: 'ABC Bank'
        immediateOriginName:
          type: string
          maxLength: 18
          description: Identifies the short name of the institution that sends the file.
          example: 'Bank One'
        fileIDModifier:
          type: string
          maxLength: 1
          description: |
            A code that permits multiple files, created on the same date, same time and between the
            same institutions, to be distinguished one from another. If all of the following fields in a previous file are
            equal to the same fields in this file: FileHeader ImmediateDestination, ImmediateOrigin, FileCreationDate, and
            FileCreationTime, it must be defined.
          example: 'A'
        countryCode:
          type: string
          maxLength: 2
          description: |
            A 2-character code as approved by the International Organization for Standardization (ISO) used
            to identify the country in which the payer bank is located.
          example: 'US'
        userField:
          type: string
          maxLength: 4
          description: Identifies a field used at the discretion of users of the standard.
          example: 'ZZZZ'
        companionDocumentIndicator:
          type: string
          maxLength: 1
          description: |
            Identifies a field used to indicate the Companion Document being used.
            Shall be present only under clearing arrangements. Companion Document usage and values
            defined by clearing arrangements.
            Values:
            0–9 Reserved for United States use
            A–J Reserved for Canadian use
            Other - as defined by clearing arrangements.
          example: '1'
      required:
        - standardLevel
        - testFileIndicator
        - resendIndicator
        - immediateDestination
        - immediateOrigin
        - fileCreationDate
        - fileCreationTime
    FileControl:
      properties:
        id:
          type: string
          description: FileControl ID
          example: d1e26288
        cashLetterCount:
          type: integer
          description: Identifies the total number of cash letters within the file.
          example: 1
        totalRecordCount:
          type: integer
          description: Identifies the total number of records of all types sent in the file, including the FileControl.
          example: 1
        totalItemCount:
          type: integer
          description: Identifies the total number of Items sent within the file.
          example: 5
        fileTotalAmount :
          type: integer
          description: Identifies the total Item amount of the complete file.
          example: 100
        immediateOriginContactName:
          type: string
          maxLength: 14
          description: Identifies contact at the institution that creates the file.
          example: 'John Smith'
        immediateOriginContactPhoneNumber:
          type: string
          maxLength: 10
          description: Identifies the phone number of the contact at the institution that creates the file.
          example: '555-555-1212'
        creditTotalIndicator:
          type: string
          maxLength: 1
          enum:
            -
            - 0
            - 1
          description: |
            Is a code that indicates whether Credits Items are included in this record’s totals. If so they will be included in TotalItemCount and FileTotalAmount.
            TotalRecordCount includes all records of all types regardless of the value of this field.
            * ` ` - No Credit Items
            * `0` - Credit Items are not included in totals
            * `1` - Credit Items are included in totals
      required:
        - cashLetterCount
        - totalRecordCount
        - totalItemCount
        - fileTotalAmount
    RawFile:
      type: string
      description: Plaintext X9 file
      example: "0135T231380104121042882201809051523NCitadel           Wells Fargo        US     "
    Files:
      type: array
      items:
        $ref: '#/components/schemas/File'
    CashLetter:
      properties:
        cashLetterHeader:
          $ref: '#/components/schemas/CashLetterHeader'
        # Current Implementation: CreditItem(s) Precede CheckDetail(s) - CreditItem(s) outside the leading Bundle
        # and Within the First Cash Letter.  Please adjust reader and writer, and openAPI for your specific clearing arrangement
        # implementation or contact MOOV for your particular implementation.
#        creditItems:
#          type: array
#          items:
#            $ref: '#/components/schemas/CreditItem'
#        bundles:
#          type: array
#          items:
#            $ref: '#/components/schemas/Bundle'
#        routingNumberSummary:
#          type: array
#          items:
#            $ref: '#/components/schemas/RoutingNumberSummary'
        cashLetterControl:
          $ref: '#/components/schemas/CashLetterControl'
    CashLetterHeader:
      properties:
        id:
          description: CashHeader ID
          type: string
          example: d1e26288
        collectionTypeIndicator:
          type: string
          maxLength: 2
          enum:
            - 00
            - 01
            - 02
            - 03
            - 04
            - 05
            - 06
            - 20
            - 99
          description: |
            CollectionTypeIndicator is a code that identifies the type of cash letter.

            * `00` - Preliminary Forward Information
            * `01` - Forward Presentment
            * `02` - Forward Presentment - Same-Day Settlement
            * `03` - Return
            * `04` - Return Notification
            * `05` - Preliminary Return Notification
            * `06` - Final Return Notification
            * `20` - No Detail
            * `99` - Bundles not the same collection type. Use of the value is only allowed by clearing arrangement.
          example:
            '00'
        destinationRoutingNumber:
          type: string
          maxLength: 9
          description: DestinationRoutingNumber is the routing and transit number of the institution that receives and processes the cash letter or the bundle.
          example: '999282654'
        eceInstitutionRoutingNumber:
          type: string
          maxLength: 9
          description: ECEInstitutionRoutingNumber is the routing and transit number of the institution that creates the Cash Letter Header record
          example : '217876527'
        cashLetterBusinessDate:
          type: string
          maxLength: 8
          description: cashLetterBusinessDate is the business date of the cash letter. (Format YYYYMMDD, where - YYYY year, MM month, DD day)
          example: '20190522'
        cashLetterCreationDate:
          type: string
          maxLength: 8
          description: cashLetterCreationDate is the date that the cash letter is created (Format YYYYMMDD, where - YYYY year, MM month, DD day)
          example: '20190522'
        cashLetterCreationTime:
          type: string
          maxLength: 4
          description: CashLetterCreationTime is the time that the cash letter is created. (Format - hhmm, where - hh hour, mm minute)
          example: '1310'
        recordTypeIndicator:
          type: string
          maxLength: 1
          enum:
            - N
            - E
            - I
            - F
          description: |
            RecordTypeIndicator is a code that indicates the presence of records or the type of records contained in the cash letter.
            If an image is associated with any CheckDetail or Return, the cash letter must have a
            RecordTypeIndicator of I or F.

            * `N` - No electronic check records or image records (Type 2x’s, 3x’s, 5x’s); e.g., an empty cash letter.
            * `E` - Cash letter contains electronic check records with no images (Type 2x’s and 3x’s only).
            * `I` - Cash letter contains electronic check records (Type 2x’s, 3x’s) and image records (Type 5x’s).
            * `F` - Cash letter contains electronic check records (Type 2x’s and 3x’s) and image records (Type 5x’s)
            that correspond to a previously sent cash letter (i.e., E file).
          example: 'N'
        documentationTypeIndicator:
          type: string
          maxLength: 1
          enum:
            - A
            - B
            - C
            - D
            - E
            - F
            - G
            - H
            - I
            - J
            - K
            - L
            - M
            - Z
          description: |
            DocumentationTypeIndicator is a code that indicates the type of documentation that supports all check records in the cash letter.

            * `A` - No image provided, paper provided separately
            * `B` - No image provided, paper provided separately, image upon request
            * `C` - Image provided separately, no paper provided
            * `D` - Image provided separately, no paper provided, image upon request
            * `E` - Image and paper provided separately
            * `F` - Image and paper provided separately, image upon request
            * `G` - Image included, no paper provided
            * `H` - Image included, no paper provided, image upon request
            * `I` - Image included, paper provided separately
            * `J` - Image included, paper provided separately, image upon request
            * `K` - No image provided, no paper provided
            * `L` - No image provided, no paper provided, image upon request
            * `M` - No image provided, Electronic Check provided separately
            * `Z` - Not Same Type–Documentation associated with each item in Cash Letter will be different.
            The Check Detail
          example: 'A'
        cashLetterID:
          type: string
          maxLength: 8
          description: CashLetterID uniquely identifies the cash letter. It is assigned by the institution that creates the cash
            letter and must be unique within a Cash Letter Business Date.
          example: '1'
        originatorContactName:
          type: string
          maxLength: 14
          description: OriginatorContactName is the name of contact at the institution that creates the cash letter.
          example: "John Smith"
        originatorContactPhoneNumber:
          type: string
          maxLength: 10
          description: OriginatorContactPhoneNumber is the phone number of the contact at the institution that creates the cash letter.
          example: '5685551212'
        fedWorkType:
          type: string
          maxLength: 1
          description: fedWorkType is any valid codes specified by the Federal Reserve Bank
          example: 'V'
        returnsIndicator:
          type: string
          maxLength: 1
          enum:
            -
            - E
            - R
            - J
          description: |
            ReturnsIndicator ddentifies type of returns

            * ` ` - Original Message
            * `E` - Administrative - items being returned that are handled by the bank and usually do not directly
            affect the customer or its account.
            * `R` - Customer–items being returned that directly affect a customer’s account.
            * `J` - Reject Return
        userField:
          type: string
          maxLength: 1
          description: UserField is a field used at the discretion of users of the standard
          example: 'V'
    CashLetterControl:
      properties:
        id:
          type: string
          description: CashLetter ID
          example: d1e26288
        cashLetterBundleCount:
          type: int
          description: CashLetterBundleCount identifies the total number of bundles within the cash letter.
          example: 1